---
title: "Comparison of mRNA log2 fold changes for stress response genes SRXN1 and DDIT3 (CHOP) across liver models, 24 hours post-NIT exposure"
author: "Tamara Danilyuk"
date: "`r Sys.Date()`"
output: 
  prettydoc::html_pretty:
    fig_width: 8
    fig_height: 6
    theme: cayman
    toc: yes
---

## Project packages 
```{r error=F, message=FALSE, warning=FALSE}

# Check if pacman is available and install
if(!require("pacman", quietly = T)){install.packages("pacman")}; library(pacman)

# use packman to install CRAN packages
p_load(tidyverse, ggpubr, corrr, ggfortify, ggcorrplot, ggdendro, data.table, GGally, viridis,dplyr)

```

## Importing and wrangling data

```{r error=F,warning=F,message=F}
nit_deseq_result <- data.table::fread(file = "F:/TD22 HLCs TempoSeq/DATA/TD22_HLCs_deseq_per_treatment_res.txt.gz", sep = "\t") 
nit_deseq_result_HepG2 <- data.table::fread(file = "F:/TD22 HLCs TempoSeq/DATA/TranscriptomicsHepG2_NITDICKET.txt", sep = "\t") 
nit_PHH_tg_gates <- data.table::fread(file = "F:/TD22 HLCs TempoSeq/DATA/TGGATES.csv", sep = ";") 

hiPSCs_reporter_gene_list=c("SRXN1","DDIT3")

# Filter and add 'Test system' column for hiPSCs-derived HLCs

hlc_data <- nit_deseq_result %>%
  filter(gene_symbol %in% hiPSCs_reporter_gene_list) %>%
  mutate(Test_system = "hiPSCs-derived HLCs")

nit_PHH_tg_gates <- nit_PHH_tg_gates %>%
  filter(gene_symbol %in% hiPSCs_reporter_gene_list) %>%
  filter(time == 24) %>%
  mutate(Test_system = "PHH")

hepg2_data <- nit_deseq_result_HepG2 %>%
  filter(concentration %in% c(120, 60, 6), gene_symbol %in% hiPSCs_reporter_gene_list, time == 24, treatment%in% c("Nitrofurantoin") ) %>%
  mutate(
    conc_level = case_when(
      concentration == 120 ~ 1,
      concentration == 60 ~ 2,
      concentration == 6 ~ 3,
      TRUE ~ NA_real_
    ),
    Test_system = "HepG2"
  )

hlc_data <- hlc_data %>%
  separate(col = "condition", into = c("treatment", "time", "conc_level"), remove = FALSE)%>%
  filter(time == 24) %>%
  filter(conc_level %in% c(1,2,3))


common_columns <- intersect(names(hlc_data), names(nit_PHH_tg_gates))
combined_data_common_hlc <- hlc_data %>% select(all_of(common_columns))%>% mutate(time = as.integer(time))%>% mutate(conc_level = as.integer(conc_level))
combined_data_common_hepg2 <- hepg2_data %>% select(all_of(common_columns))%>% mutate(time = as.integer(time))%>% mutate(conc_level = as.integer(conc_level))
nit_PHH_tg_gates_common <- nit_PHH_tg_gates %>% select(all_of(common_columns))%>% mutate(time = as.integer(time))%>% mutate(conc_level = as.integer(conc_level))
combined_data_common <- bind_rows(combined_data_common_hlc, 
                           combined_data_common_hepg2, 
                           nit_PHH_tg_gates_common)

combined_data_common <- combined_data_common %>%
  group_by(gene_symbol, conc_level, Test_system) %>%
  summarize(
    log2FoldChange = mean(log2FoldChange, na.rm = TRUE),
    avg_pvalue = mean(pvalue, na.rm = TRUE)
  ) %>%
  mutate(
    significance = case_when(
      avg_pvalue < 0.001 ~ "***",
      avg_pvalue < 0.01 ~ "**",
      avg_pvalue < 0.05 ~ "*",
      TRUE ~ ""
    )
  ) %>%
  ungroup()  # Remove grouping to get a final dataset


combined_data_common$log2FoldChange<-as.numeric(combined_data_common$log2FoldChange)
```

## Plot combined data

```{r error=F,warning=F,message=F}
p6 <- ggplot(data = combined_data_common, 
             mapping = aes(x = factor(conc_level), y = log2FoldChange, fill = Test_system)) + 
    geom_bar(stat = "identity", position = position_dodge(width = 0.9)) + 
    facet_wrap(~ gene_symbol, scales = "fixed", ncol = 2) +
    geom_hline(yintercept = 0.6, linetype = "solid", color = "red") +
    scale_fill_viridis(discrete = TRUE, option = "D") +
    theme_bw() +
    theme(
        strip.text = element_text(size = 15, color = "black", face = "plain"),  # Changed to plain
        plot.title = element_text(size = 18, hjust = 0.5),
        axis.title = element_text(size = 18),  # Increased size
        axis.text = element_text(size = 16),  # Increased size for both x and y axis text
        legend.position = "right",
        legend.title = element_blank(),
        legend.text = element_text(size = 15)
    ) +
    labs(x = "Concentration Level", y = "log2 Fold Change") +
    scale_x_discrete(limits = c("3", "2", "1"), labels = c("3" = "Low", "2" = "Medium", "1" = "High")) +
    scale_y_continuous(limits = c(-0.39, 3.6)) +
    geom_text(aes(label = significance), 
              position = position_dodge(width = 0.9), 
              vjust = -1, size = 4, color = "black")

# Print the plot
print(p6)

# Specify the file path to save p6
file_path <- "F:/TD22 HLCs TempoSeq/DATA/Stress_response_genes_baseline_correct.pdf"

# Save the plot as a PDF file
ggsave(file_path, plot = p6, width = 25, height = 16, units = "cm", dpi = 300)

```





