---
title: "Data analysis - Transcriptomics data"
author: "Elsje Burgers"
last modified: "2024-12-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r}
rm(list = ls())

library(tidyverse)

SaveFigures = 0
```

# Load data
```{r}
data = read.csv("../Data/Transcriptomics/TranscriptomicsHepG2_NITDICKET.csv", header = TRUE) %>%
  filter(TimePoint>4)
```

# Select gene  
```{r}
gene = c("CHAC1")
data_f = filter(data, GeneSymbol == gene & TimePoint == 8)
```

# plot NIT gene at 8 hrs
```{r}
data_f_NIT = filter(data_f, TREATMENT %in% c("NIT", "NIT2")) %>%
  mutate(concentration = round(concentration)) %>%
  filter(concentration < 200)
  
data_f_NIT_mean = data_f_NIT %>%
  group_by(GeneSymbol, EntrezID, TimePoint, concentration) %>%
  summarize(log2fc = mean(log2fc),
            StdError = sqrt(sum(StdError^2)/2)) %>%
  ungroup() %>%
  add_column(TREATMENT = "NIT")

plot_3c = ggplot(data_f_NIT_mean) + theme_classic(base_size = 13) +
  geom_bar(aes(x = as.factor(concentration), y = log2fc, fill = as.factor(concentration)),
           position=position_dodge(), stat="identity") +
  geom_errorbar(aes(x = as.factor(concentration), ymin = log2fc-StdError, ymax = log2fc+StdError), width=.2) +
  scale_fill_viridis_d() + xlab(expression(paste("Dose (", mu, "M)"))) + ylab("CHAC1 log2 Fold Change") +
  theme(legend.position = "none")

print(plot_3c)


if(SaveFigures == 1){
  ggsave("Figure3c.svg", plot = plot_3c, path = "..//Figures", width = 8,
         height = 8, units = "cm", dpi = 300)
}

# data_f_DIC = filter(data_f, TREATMENT %in% c("DIC")) %>%
#   mutate(concentration = round(concentration)) %>%
#   filter(concentration < 500) %>%
#   rename(log2fc = log2fc) %>%
#   select(GeneSymbol, EntrezID, TimePoint, concentration, log2fc, StdError, TREATMENT)
# 
# data_f_KET = filter(data_f, TREATMENT %in% c("KET")) %>%
#   mutate(concentration = round(concentration)) %>%
#   filter(concentration < 100) %>%
#   rename(log2fc = log2fc) %>%
#     select(GeneSymbol, EntrezID, TimePoint, concentration, log2fc, StdError, TREATMENT)
# 
# 
# data_f_DICKET = rbind(data_f_DIC, data_f_KET) %>%
#   filter(TimePoint == 24)
# 
# plot = ggplot(data_f_DICKET) + theme_classic(base_size = 13) +
#   geom_bar(aes(x = as.factor(concentration), y = log2fc, fill = as.factor(concentration)),
#            position=position_dodge(), stat="identity") +
#   geom_errorbar(aes(x = as.factor(concentration), ymin = log2fc-StdError, ymax = log2fc+StdError), width=.2) +
#   scale_fill_viridis_d() + xlab(expression(paste("Dose (", mu, "M)"))) + ylab("log2 Fold Change") +
#   theme(legend.position = "none") + facet_grid(rows = vars(GeneSymbol), cols = vars(TREATMENT), scales = "free_x")
# print(plot)

```
# Select gene  
```{r}
gene = c("GCLC", "GCLM", "CHAC1")
data_f = filter(data, GeneSymbol %in% gene)
```

# plot NIT gene at 8 and 24 hrs
```{r}
data_f_NIT = filter(data_f, TREATMENT %in% c("NIT", "NIT2")) %>%
  mutate(concentration = round(concentration)) %>%
  filter(concentration < 200)
  
data_f_NIT_mean = data_f_NIT %>%
  group_by(GeneSymbol, EntrezID, TimePoint, concentration) %>%
  summarize(log2fc = mean(log2fc),
            StdError = sqrt(sum(StdError^2)/2)) %>%
  ungroup() %>%
  add_column(TREATMENT = "NIT")

data_f_DIC = filter(data_f, TREATMENT %in% c("DIC")) %>%
  mutate(concentration = round(concentration)) %>%
  filter(concentration < 500) %>%
  rename(log2fc = log2fc) %>%
  select(GeneSymbol, EntrezID, TimePoint, concentration, log2fc, StdError, TREATMENT)

data_f_KET = filter(data_f, TREATMENT %in% c("KET")) %>%
  mutate(concentration = round(concentration)) %>%
  filter(concentration < 100) %>%
  rename(log2fc = log2fc) %>%
    select(GeneSymbol, EntrezID, TimePoint, concentration, log2fc, StdError, TREATMENT)


data_f_NITDICKET = rbind(data_f_NIT_mean, data_f_DIC, data_f_KET) %>%
  filter(TimePoint == 24)


plot_S13 = ggplot(data_f_NITDICKET) + theme_classic(base_size = 13) +
  geom_bar(aes(x = as.factor(concentration), y = log2fc, fill = as.factor(concentration)),
           position=position_dodge(), stat="identity") +
  geom_errorbar(aes(x = as.factor(concentration), ymin = log2fc-StdError, ymax = log2fc+StdError), width=.2) +
  scale_fill_viridis_d() + xlab(expression(paste("Dose (", mu, "M)"))) + ylab("log2 Fold Change") +
  theme(legend.position = "none") + facet_grid(rows = vars(GeneSymbol), cols = vars(TREATMENT), scales = "free_x")
print(plot_S13)


if(SaveFigures == 1){
  ggsave("FigureS13.pdf", plot = plot_S13, path = "..//Figures", width = 15,
         height = 14, units = "cm", dpi = 300)
}

```

<!-- # Select gene   -->
<!-- ```{r} -->
<!-- gene = c("ATF3", "DDIT3", "TRIB3", "SRXN1") -->
<!-- data_f = filter(data, GeneSymbol %in% gene) -->
<!-- ``` -->

<!-- # plot NIT gene at 8 and 24 hrs -->
<!-- ```{r} -->
<!-- data_f_NIT = filter(data_f, TREATMENT %in% c("NIT", "NIT2")) %>% -->
<!--   mutate(concentration = round(concentration)) %>% -->
<!--   filter(concentration < 200) -->

<!-- data_f_NIT_mean = data_f_NIT %>% -->
<!--   group_by(GeneSymbol, EntrezID, TimePoint, concentration) %>% -->
<!--   summarize(log2fc = mean(log2fc), -->
<!--             StdError = sqrt(sum(StdError^2)/2)) %>% -->
<!--   ungroup() %>% -->
<!--   add_column(TREATMENT = "NIT") -->

<!-- data_f_DIC = filter(data_f, TREATMENT %in% c("DIC")) %>% -->
<!--   mutate(concentration = round(concentration)) %>% -->
<!--   filter(concentration < 500) %>% -->
<!--   rename(log2fc = log2fc) %>% -->
<!--   select(GeneSymbol, EntrezID, TimePoint, concentration, log2fc, StdError, TREATMENT) -->

<!-- data_f_KET = filter(data_f, TREATMENT %in% c("KET")) %>% -->
<!--   mutate(concentration = round(concentration)) %>% -->
<!--   filter(concentration < 100) %>% -->
<!--   rename(log2fc = log2fc) %>% -->
<!--     select(GeneSymbol, EntrezID, TimePoint, concentration, log2fc, StdError, TREATMENT) -->


<!-- data_f_NITDICKET = rbind(data_f_NIT_mean, data_f_DIC, data_f_KET)  -->


<!-- plot = ggplot(data_f_NITDICKET %>% filter(TimePoint == 8)) + theme_classic(base_size = 13) + -->
<!--   geom_bar(aes(x = as.factor(concentration), y = log2fc, fill = as.factor(concentration)), -->
<!--            position=position_dodge(), stat="identity") + -->
<!--   geom_errorbar(aes(x = as.factor(concentration), ymin = log2fc-StdError, ymax = log2fc+StdError), width=.2) + -->
<!--   scale_fill_viridis_d() + xlab(expression(paste("Dose (", mu, "M)"))) + ylab("log2 Fold Change") + -->
<!--   theme(legend.position = "none") + facet_grid(rows = vars(GeneSymbol), cols = vars(TREATMENT), scales = "free_x") -->
<!-- print(plot) -->

<!-- plot = ggplot(data_f_NITDICKET %>% filter(TimePoint == 24)) + theme_classic(base_size = 13) + -->
<!--   geom_bar(aes(x = as.factor(concentration), y = log2fc, fill = as.factor(concentration)), -->
<!--            position=position_dodge(), stat="identity") + -->
<!--   geom_errorbar(aes(x = as.factor(concentration), ymin = log2fc-StdError, ymax = log2fc+StdError), width=.2) + -->
<!--   scale_fill_viridis_d() + xlab(expression(paste("Dose (", mu, "M)"))) + ylab("log2 Fold Change") + -->
<!--   theme(legend.position = "none") + facet_grid(rows = vars(GeneSymbol), cols = vars(TREATMENT), scales = "free_x") -->
<!-- print(plot) -->


<!-- if(SaveFigures == 1){ -->
<!--   ggsave("Figure3c.svg", plot = plot, path = "..//Figures", width = 10, -->
<!--          height = 8, units = "cm", dpi = 300) -->
<!-- } -->

<!-- ``` -->
<!-- # Select gene   -->
<!-- ```{r} -->
<!-- gene = c("SRXN1") -->
<!-- data_f = filter(data, GeneSymbol == gene) -->
<!-- ``` -->

<!-- # plot NIT gene at 8 and 24 hrs -->
<!-- ```{r} -->
<!-- data_f_NIT = filter(data_f, TREATMENT %in% c("NIT", "NIT2")) %>% -->
<!--   mutate(concentration = round(concentration)) %>% -->
<!--   filter(concentration < 200) -->

<!-- data_f_NIT_mean = data_f_NIT %>% -->
<!--   group_by(GeneSymbol, EntrezID, TimePoint, concentration) %>% -->
<!--   summarize(log2fc = mean(log2fc), -->
<!--             StdError = sqrt(sum(StdError^2)/2)) %>% -->
<!--   ungroup() %>% -->
<!--   add_column(TREATMENT = "NIT") -->

<!-- plot_3c = ggplot(data_f_NIT_mean) + theme_classic(base_size = 13) + -->
<!--   geom_bar(aes(x = as.factor(concentration), y = log2fc, fill = as.factor(concentration)), -->
<!--            position=position_dodge(), stat="identity") + -->
<!--   geom_errorbar(aes(x = as.factor(concentration), ymin = log2fc-StdError, ymax = log2fc+StdError), width=.2) + -->
<!--   scale_fill_viridis_d() + xlab(expression(paste("Dose (", mu, "M)"))) + ylab("CHAC1 log2 Fold Change") + -->
<!--   theme(legend.position = "none") + facet_grid(cols = vars(TimePoint)) -->

<!-- print(plot_3c) -->


<!-- if(SaveFigures == 1){ -->
<!--   ggsave("Figure3c.svg", plot = plot_3c, path = "..//Figures", width = 10, -->
<!--          height = 8, units = "cm", dpi = 300) -->
<!-- } -->

<!-- data_f_DIC = filter(data_f, TREATMENT %in% c("DIC")) %>% -->
<!--   mutate(concentration = round(concentration)) %>% -->
<!--   filter(concentration < 500) %>% -->
<!--   rename(log2fc = log2fc) %>% -->
<!--   select(GeneSymbol, EntrezID, TimePoint, concentration, log2fc, StdError, TREATMENT) -->

<!-- data_f_KET = filter(data_f, TREATMENT %in% c("KET")) %>% -->
<!--   mutate(concentration = round(concentration)) %>% -->
<!--   filter(concentration < 100) %>% -->
<!--   rename(log2fc = log2fc) %>% -->
<!--     select(GeneSymbol, EntrezID, TimePoint, concentration, log2fc, StdError, TREATMENT) -->


<!-- data_f_DICKET = rbind(data_f_DIC, data_f_KET) %>% -->
<!--   filter(TimePoint == 24) -->

<!-- plot = ggplot(data_f_DICKET) + theme_classic(base_size = 13) + -->
<!--   geom_bar(aes(x = as.factor(concentration), y = log2fc, fill = as.factor(concentration)), -->
<!--            position=position_dodge(), stat="identity") + -->
<!--   geom_errorbar(aes(x = as.factor(concentration), ymin = log2fc-StdError, ymax = log2fc+StdError), width=.2) + -->
<!--   scale_fill_viridis_d() + xlab(expression(paste("Dose (", mu, "M)"))) + ylab("log2 Fold Change") + -->
<!--   theme(legend.position = "none") + facet_grid(rows = vars(GeneSymbol), cols = vars(TREATMENT), scales = "free_x") -->
<!-- print(plot) -->

<!-- ``` -->
